ARG GIT_TAG=${GIT_TAG:-master}

FROM python:3.10-slim AS app

ARG GIT_TAG

COPY --from=ceramicwhite/gotty /usr/bin/gotty /bin/gotty

ENV PIP_NO_CACHE_DIR=yes \
    PYTHONUNBUFFERED=1 \
    PYTHONDONTWRITEBYTECODE=1 \
    HEADLESS_BROWSER=True \
    HOME=/app \
    PATH="${PATH}:/app/.local/bin"

WORKDIR /app

RUN apt-get -y update && \
    apt-get -y install \
    git \
    chromium-driver \
    apt-utils \
    wget \
    curl \
    jq \
    unzip \
    gnupg2 \
    libgtk-3-0 \
    libdbus-glib-1-2 \
    dbus-x11 \
    xvfb \
    ca-certificates && \
    case $(uname -m) in x86_64) OS=amd64 ;; aarch64) OS=arm64 ;; *) exit 1 ;; esac && \
    wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add - && \
    echo "deb [arch=$OS] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list && \
    apt-get update && \
    apt-get install -y chromium firefox-esr && \
    git clone -b ${GIT_TAG} --depth 1 https://github.com/Significant-Gravitas/Auto-GPT.git . && \
    pip install --upgrade pip && \
    pip install --no-cache-dir --user -r requirements.txt && \
    sed -i '/self.openai_api_key = os.getenv("OPENAI_API_KEY")/i \        self.api_base = os.getenv\("OPENAI_API_BASE", "https:\/\/api.openai.com\/v1"\)' autogpt/config/config.py && \
    sed -i '/self.browse_chunk_max_length = int(os.getenv("BROWSE_CHUNK_MAX_LENGTH", 3000))/a \        self.embed_dim = int\(os.getenv\("EMBED_DIM", 1536\)\)' autogpt/config/config.py

EXPOSE 3000

ENTRYPOINT ["gotty", "--port", "3000", "--permit-write", "--title-format", "AutoGPT Terminal"]
CMD ["python", "-m", "autogpt"]
