ARG GIT_TAG=${GIT_TAG:-master}

FROM ceramicwhite/auto-gpt:${GIT_TAG} AS app

ENV OPENAI_API_KEY=sk-N \
    ALLOWLISTED_PLUGINS=SystemInformationPlugin \
    EXECUTE_LOCAL_COMMANDS=True

RUN mv .env.template .env && \
    mkdir -p plugins && \
    pip install --no-cache-dir --user notion-client python-dotenv auto_gpt_plugin_template ta myfxbook gaapi4py web3 eth-account ccxt telethon uniswap-python && \
    curl -L -o ./plugins/Auto-GPT-Plugins.zip https://github.com/Significant-Gravitas/Auto-GPT-Plugins/archive/refs/heads/master.zip && \
    curl -L -o ./plugins/Auto-GPT-SystemInfo.zip https://github.com/hdkiller/Auto-GPT-SystemInfo/archive/refs/heads/master.zip && \     
    curl -L -o ./plugins/Auto-GPT-Notion.zip https://github.com/doutv/Auto-GPT-Notion/archive/refs/heads/master.zip && \
    curl -L -o ./plugins/Auto-GPT-Telegram.zip https://github.com/Wladastic/Auto-GPT-Telegram-Plugin/archive/refs/heads/master.zip && \
    curl -L -o ./plugins/Auto-GPT-MetaTrader.zip https://github.com/isaiahbjork/Auto-GPT-MetaTrader-Plugin/archive/refs/heads/master.zip && \
    curl -L -o ./plugins/Auto-GPT-Google-Analytics.zip https://github.com/isaiahbjork/Auto-GPT-Google-Analytics-Plugin/archive/refs/heads/master.zip && \
    curl -L -o ./plugins/AutoGPT-YouTube.zip https://github.com/jpetzke/AutoGPT-YouTube/archive/refs/heads/master.zip && \
    curl -L -o ./plugins/AutoGPT-Mastodon-Plugin.zip https://github.com/ppetermann/AutoGPTMastodonPlugin/archive/refs/heads/master.zip && \
    curl -L -o ./plugins/Auto-GPT-TiDB-Serverless-Plugin.zip https://github.com/pingcap/Auto-GPT-TiDB-Serverless-Plugin/archive/refs/heads/master.zip && \
    curl -L -o ./plugins/AutoGPT-Instagram-Plugin.zip https://github.com/jpetzke/AutoGPT-Instagram/archive/refs/heads/master.zip && \
    curl -L -o ./plugins/Auto-GPT-Crypto-Plugin.zip https://github.com/isaiahbjork/Auto-GPT-Crypto-Plugin/archive/refs/heads/master.zip && \
    curl -L -o ./plugins/Auto-GPT-Messages-Plugin.zip https://github.com/danikhan632/Auto-GPT-Messages-Plugin/archive/refs/heads/master.zip && \
    curl -L -o ./plugins/Auto-GPT-AlpacaTrader-Plugin.zip https://github.com/danikhan632/Auto-GPT-AlpacaTrader-Plugin/archive/refs/heads/master.zip && \
    yes | ./run.sh --install-plugin-deps
