ARG GIT_TAG=${GIT_TAG:-master}

FROM python:3.10-slim AS app

ARG GIT_TAG

COPY --from=ceramicwhite/gotty /usr/bin/gotty /bin/gotty

ENV PIP_NO_CACHE_DIR=yes \
    PYTHONUNBUFFERED=1 \
    PYTHONDONTWRITEBYTECODE=1 \
    HEADLESS_BROWSER=True \
    EXECUTE_LOCAL_COMMANDS=True \
    HOME=/app \
    PATH="${PATH}:/app/.local/bin"

WORKDIR /app

RUN apt-get -y update && \
    apt-get -y install \
    git \
    wget \
    curl \
    jq \
    sudo \
    unzip \
    chromium-driver \
    firefox-esr \
    ca-certificates && \
    git clone -b ${GIT_TAG} --depth 1 https://github.com/Significant-Gravitas/Auto-GPT.git . && \
    pip install --upgrade pip ; \
    if [ "${GIT_TAG}" != "master" ]; then \
        sed -i '/Items below this point will not be included in the Docker Image/,$d' requirements.txt; \
    fi ; \
    pip install --no-cache-dir -r requirements.txt && \
    sed -i '/self.openai_api_key = os.getenv("OPENAI_API_KEY")/i \        self.api_base = os.getenv\("OPENAI_API_BASE", "https:\/\/api.openai.com\/v1"\)' autogpt/config/config.py && \
    sed -i '/self.browse_chunk_max_length = int(os.getenv("BROWSE_CHUNK_MAX_LENGTH", 3000))/a \        self.embed_dim = int\(os.getenv\("EMBED_DIM", 1536\)\)' autogpt/config/config.py && \
    curl -L -o ./entrypoint.sh https://raw.githubusercontent.com/ceramicwhite/Auto-GPT/master/.github/workflows/dockerfiles/entrypoint.sh && \
    chmod +x entrypoint.sh

EXPOSE 3000

ENTRYPOINT ["/app/entrypoint.sh"]
